import type { Metadata } from "next";
import localfont from 'next/font/local'
import { Poppins } from "next/font/google";
import "./globals.css";


const inter = Poppins({ subsets: ["latin"], weight: '400' });

const histeagin = localfont({
  src: [
    {
      path: '../public/Font/histeagin.ttf',
      weight: '300'
    },
  ],
  variable: "--font-histeagin"
}
)

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${histeagin.variable} bg-black `} >
      <body className={inter.className}>{children}</body>
    </html>
  );
}
